config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' 

  resources :employees
  resources :companies
  #resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :employee, dependent: :destroy 

    mount_uploader :logo, LogoUploader
    # we also must check uniqueness of name on the database side
    validates :name, presence: true, length: { minimum: 2, maximum: 100 }, uniqueness: true

    validates :email, length: { maximum: 100 }, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'Requires a valid email format' }, allow_blank: true

    validates :website, length: { maximum: 100 }, allow_blank: true
    
end  

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company

  validates :first_name, presence: true, length: { minimum: 2, maximum: 100 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 100 }
  validates :email, length: { maximum: 100 }, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'Requires a valid email format' }, allow_blank: true
  validates :phone, phone: { allow_blank: true }

  validates :company_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :password, presence: true

    validates :email, presence: true,                   
                      format: /\A\S+@\S+\z/,
                      uniqueness: { case_sensitive: false }
                      
    def self.authenticate(email, password)
        user = User.find_by(email: email)
        user && user.authenticate(password)
    end                  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Also by default a production application will render either a 404 or a 500 error message.
  before_action :set_no_cache

  def index
    
  end

protected  
  def set_no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

private
  
  def must_be_not_authenticated
    unless session[:user_id].nil?
        redirect_to companies_path
    end
  end

  def is_authenticated?
    session[:user_id].present?
  end

  helper_method :is_authenticated?

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to login_path, alert: "Please sign in first!"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def require_admin
    unless current_user_admin?
      redirect_to login_path, alert: "Unauthorized access!"
    end
  end

  def current_user_admin?  
    current_user && current_user.admin?
  end

  helper_method :current_user_admin?
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :require_signin
    before_action :require_admin
    around_action :catch_not_found

    def index
        @companies = Company.paginate(page: params[:page], per_page: 1).order('created_at DESC')
    end

    def new
        @company = Company.new
    end

    def create
        @company = Company.new(resume_params)
        
        if @company.save
            flash.notice = "The company #{@company.name} has been uploaded."
            redirect_to companies_path
        else
            render :new  
        end
    end

    def show
         @company = Company.find(params[:id])
    end

    def edit
        @company = Company.find(params[:id]) 
    end

    def update
        @company = Company.find_by(id: params[:id])
        if @company.update(resume_params)
            redirect_to @company, notice: "Company successfully updated!"
        else
            render :edit
        end
    end

    def destroy
        current_company = Company.find(params[:id])
        name = current_company.name 
        id = current_company.id
        current_company.destroy
        FileUtils.remove_dir("#{Rails.root}/public/uploads/company/logo/#{id}", :force => true)
        redirect_to companies_path, notice: "#{name} deleted." 
    end

private 

    def resume_params
        params.require(:company).permit(:name, :email, :website, :logo)
    end

    def catch_not_found
        yield
        rescue ActiveRecord::RecordNotFound
            redirect_to root_path, :flash => { :error => "Record not found." }
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :require_signin
    before_action :require_admin
    around_action :catch_not_found

    def index
        @employees = Employee.paginate(page: params[:page], per_page: 1).order('created_at DESC')
    end


    def new
        @employee = Employee.new
        @companies = Company.all.order('created_at DESC')
    end


    def create
        @employee = Employee.new(resume_params)
        @companies = Company.all.order('created_at DESC')
        if @employee.save
            flash.notice = "New Employee was added to the #{@employee.company.name} company: #{@employee.first_name}"
            redirect_to employees_path
        else
            render :new  
        end
    end

    def show
        @employee = Employee.find(params[:id])
   end

   def edit
        @employee = Employee.find(params[:id]) 
        @companies = Company.all.order('created_at DESC')
   end


    def update
        @employee = Employee.find_by(id: params[:id])
        if @employee.update(resume_params)
            redirect_to @employee, notice: "Employee successfully updated!"
        else
            render :edit
        end
    end

    def destroy
        name = Employee.find(params[:id]).first_name 
        Employee.find(params[:id]).destroy
        redirect_to employees_path, notice: "#{name} deleted." 
    end

private 
    
    def resume_params
        params.require(:employee).permit(:first_name, :last_name, :email, :phone, :company_id)
    end
    
    def catch_not_found
        yield
        rescue ActiveRecord::RecordNotFound
            redirect_to root_path, :flash => { :error => "Record not found." }
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :must_be_not_authenticated, only: [:new, :create]


    def new
    end

    def create
        if user = User.authenticate(params[:email], params[:password])
          session[:user_id] = user.id
          flash[:notice] = "Welcome back, #{user.email}!"
          redirect_to(session[:intended_url] || companies_path)
          session[:intended_url] = nil
        else
          flash.now[:alert] = "Invalid email/password combination!"
          render :new
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to login_path, notice: "You're now signed out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<% if flash[:error] %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong><%= flash[:error] %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>


<h1>Home Page</h1>

app/views/companies/edit.html.erb
<div class="container mt-4">
    <div class="row">
        <div class="col-offset-md-2 col-md-5">
            <%= form_for @company, html: { multipart: true } do |f| %>
                <%= render "shared/errors", object: @company %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, :autofocus => true, :class => "form-control", 'aria-describedby' => "nameHelp", :value => @company.name %>
                    <small id="nameHelp" class="form-text text-muted">Required field</small>
                </div>
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, :class => "form-control", :value => @company.email %>
                </div>
                <div class="form-group">
                    <%= f.label :website %>
                    <%= f.text_field :website, :class => "form-control", :value => @company.website %>
                </div>
                <div class="image_wrapper">
                    <p>Logo:</p>
                    <img style="object-fit: cover; width: 100px; height: 100px;" class="card-img-top img-responsive" src="<%= @company.logo_url.nil? ? 'https://bavariancarcare.com/wp-content/uploads/2019/12/image-placeholder-1200x800-1.jpg' : @company.logo_url%>" alt="logo">
                </div>
                <hr>
                <div class="custom-file">
                    <p>For New Logo:</p>
                    <%= f.file_field :logo %>
                </div>
                <hr>
                <%= f.submit "Save", class: "btn btn-primary" %>
                <%= link_to "Back To Companies", companies_path, class: 'btn btn-secondary' %>
            <% end %>    
        </div>        
    </div>
</div>

app/views/companies/index.html.erb
<!-- Modal -->
<div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You will delete all information about this Company, including Employee data.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="" id="delete_form" method="POST">
            <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
            <input name="_method" type="hidden" value="delete" />
            <button type="submit" id="delete-btn" class="btn btn-danger">Delete anyway!</button>
        </form>
      </div>
    </div>
  </div>
</div>








<div class="container mt-4">

    <div class="row">

        <div class="col-md-offset-2 col-md-9">
            <% if flash[:notice] %>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong><%= flash[:notice] %></strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <% end %>
            <h2>Companies</h2>
            <%= link_to "Add New Company", new_company_path, class: "btn btn-info", role: "button" %>
            <hr>
            <div class="card">

                <div class="card-body">
                    <% if @companies.size == 0 %>
                        <p>There is no companies yet...</p>
                    <% end %>

                    <table class="table table-dark" style="width: 100%; table-layout: fixed;">
                        <thead>
                            <tr>
                            <th scope="col" style="width: 10%;">Id</th>
                            <th scope="col" style="width: 22.5%;">Name</th>
                            <th scope="col" style="width: 22.5%;">Email</th>
                            <th scope="col" style="width: 22.5%;">Website</th>
                            <th scope="col" style="width: 22.5%;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        
                            <% @companies.each do |company| %> 

                                <tr>
                                    <th scope="row"><%= company.id %></th>
                                    <td><%= company.name %></td>
                                    <td><%= company.email %></td>
                                    <td><%= company.website %></td>
                                    <td>
                                        <%= link_to "Show", company_path(company.id), class: "btn btn-sm btn-success", role: "button" %>
                                        <%= link_to "Edit", edit_company_path(company.id), class: "btn btn-sm btn-primary", role: "button" %>
                                        <a href="#" data-company-id="<%= company.id %>" data-company-title="<%= company.name %>" data-toggle="modal" data-target="#delete_modal" role="button" class="btn btn-sm btn-danger">Delete</a>

                                    </td>
                                </tr>
                            
                            <% end %> 

                        </tbody>
                    
                    </table>
                    <div class="digg_pagination">
                        <div class="page_info">
                            <%= page_entries_info @companies %>
                        </div>
                        <%= will_paginate @companies, :container => false %>
                    </div>
                </div>

            </div>
        </div>

    </div>

</div>

<script>
    
    $('#delete_modal').on('show.bs.modal', function(e) {
        let data = $(e.relatedTarget).data();
        let actionRoute = "/companies/"+data.companyId;
        $(this).find('#deleteModalLabel').text(`Confirm to deleting the "${data.companyTitle}" company`);
        $('#delete_form').attr('action', actionRoute);
            
    });
</script>

app/views/companies/new.html.erb
<div class="container mt-4">
    <div class="row">
        <div class="col-offset-md-2 col-md-5">
            <%= form_for @company, html: { multipart: true } do |f| %>
                <%= render "shared/errors", object: @company %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, :autofocus => true, :class => "form-control", 'aria-describedby' => "nameHelp", :placeholder => "Enter Name" %>
                    <small id="nameHelp" class="form-text text-muted">Required field</small>
                </div>
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, :class => "form-control", :placeholder => "Email" %>
                </div>
                <div class="form-group">
                    <%= f.label :website %>
                    <%= f.text_field :website, :class => "form-control", :placeholder => "Website" %>
                </div>
                <div class="custom-file">
                    <%= f.label :logo %>
                    <%= f.file_field :logo %>
                </div>
                <hr>
                <%= f.submit "Save", class: "btn btn-primary" %>
                <%= link_to "Back To Companies", companies_path, class: 'btn btn-secondary' %>
            <% end %>    
        </div>        
    </div>
</div>

app/views/companies/show.html.erb
<div class="container mt-4">
    
    <div class="row">
        <div class="col-offset-md-2 col-md-5">
            <% if flash[:notice] %>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>New Company Was Added:</strong>
                        <%= flash[:notice] %>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <% end %>
        <form id="add_company_form">
            <%= render "shared/errors", object: @company %>
            <div class="form-group">
                <label for="input_name">Name</label>
                <input readonly type="text" class="form-control" id="input_name" value="<%= @company.name %>">
            </div>
            <div class="form-group">
                <label for="input_email">Email</label>
                <input readonly type="text" class="form-control" id="input_email" value="<%=@company.email%>">
            </div>
            <div class="form-group">
                <label for="input_website">Website</label>
                <input readonly type="text" class="form-control" id="input_website" value="<%=@company.website%>">
            </div>
            <div class="image_wrapper">
                <p>Logo:</p>
                <img style="object-fit: cover; width: 100px; height: 100px;" class="card-img-top img-responsive" src="<%= @company.logo_url.nil? ? 'https://bavariancarcare.com/wp-content/uploads/2019/12/image-placeholder-1200x800-1.jpg' : @company.logo_url%>" alt="logo">
            </div>
            <hr>
            <%= link_to "Back To Companies", companies_path, class: 'btn btn-secondary' %>
        </form>
        </div>    
    </div>
</div>

app/views/employees/edit.html.erb
<div class="container mt-4">
    <div class="row">
        <div class="col-offset-md-2 col-md-5">
            <%= form_for @employee, html: { multipart: true } do |f| %>
                <%= render "shared/errors", object: @employee %>
                <div class="form-group">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name, :autofocus => true, :class => "form-control", 'aria-describedby' => "first_nameHelp", :placeholder => "Enter First Name" %>
                    <small id="first_nameHelp" class="form-text text-muted">Required field</small>
                </div>
                <div class="form-group">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name, :autofocus => true, :class => "form-control", 'aria-describedby' => "last_nameHelp", :placeholder => "Enter Last Name" %>
                    <small id="last_nameHelp" class="form-text text-muted">Required field</small>
                </div>
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, :class => "form-control", :placeholder => "Email"%>
                </div>
                <div class="form-group">
                    <%= f.label :phone %>
                    <%= f.text_field :phone, :class => "form-control", :placeholder => "Phone" %>
                </div>
                <%= f.label :company_id %>
                <select class="form-control" name="employee[company_id]">
                    <% @companies.each do |company| %> 
                        <option <%= company.id == @employee.company.id ? "selected" : "" %> value="<%= company.id %>"><%=  company.name %></option>
                    <% end %>
                </select>
                <hr>
                <%= f.submit "Save", class: "btn btn-primary" %>
                <%= link_to "Back To Employees", employees_path, class: 'btn btn-secondary' %>
            <% end %>    
        </div>        
    </div>
</div>

app/views/employees/index.html.erb
<!-- Modal -->
<div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You will delete all information about this Employee.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="" id="delete_form" method="POST">
            <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
            <input name="_method" type="hidden" value="delete" />
            <button type="submit" id="delete-btn" class="btn btn-danger">Delete anyway!</button>
        </form>
      </div>
    </div>
  </div>
</div>








<div class="container mt-4">

    <div class="row">

        <div class="col-md-offset-2 col-md-9">
            <% if flash[:notice] %>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong><%= flash[:notice] %></strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <% end %>
            <h2>Employees</h2>
            <%= link_to "Add New Employee", new_employee_path, class: "btn btn-info", role: "button" %>
            <hr>
            <div class="card">

                <div class="card-body">
                    <% if @employees.size == 0 %>
                        <p>There is no employees yet...</p>
                    <% end %>

                    <table class="table table-dark" style="width: 100%; table-layout: fixed;">
                        <thead>
                            <tr>
                            <th scope="col" style="width: 10%;">Id</th>
                            <th scope="col" style="width: 15%;">First Name</th>
                            <th scope="col" style="width: 15%;">Last Name</th>
                            <th scope="col" style="width: 15%;">Email</th>
                            <th scope="col" style="width: 15%;">Phone</th>
                            <th scope="col" style="width: 15%;">Company</th>
                            <th scope="col" style="width: 15%;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        
                            <% @employees.each do |employee| %> 

                                <tr>
                                    <th scope="row"><%= employee.id %></th>
                                    <td><%= employee.first_name %></td>
                                    <td><%= employee.last_name %></td>
                                    <td><%= employee.email %></td>
                                    <td><%= employee.phone %></td>
                                    <td><%= employee.company.name %></td>
                                    <td>
                                        <%= link_to "Show", employee_path(employee.id), class: "btn btn-sm btn-success", role: "button" %>
                                        <%= link_to "Edit", edit_employee_path(employee.id), class: "btn btn-sm btn-primary", role: "button" %>
                                        <a href="#" data-employee-id="<%= employee.id %>" data-employee-title="<%= employee.first_name %>" data-toggle="modal" data-target="#delete_modal" role="button" class="btn btn-sm btn-danger">Delete</a>

                                    </td>
                                </tr>
                            
                            <% end %> 

                        </tbody>
                    
                    </table>
                    <div class="digg_pagination">
                        <div class="page_info">
                            <%= page_entries_info @employees %>
                        </div>
                        <%= will_paginate @employees, :container => false %>
                    </div>
                </div>

            </div>
        </div>

    </div>

</div>


<script>

    $('#delete_modal').on('show.bs.modal', function(e) {
        let data = $(e.relatedTarget).data();
        let actionRoute = "/employees/"+data.employeeId;
        $(this).find('#deleteModalLabel').text(`Confirm to deleting the "${data.employeeTitle}" employee`);
        $('#delete_form').attr('action', actionRoute);
    });

</script>

app/views/employees/new.html.erb
<div class="container mt-4">
    <div class="row">
        <div class="col-offset-md-2 col-md-5">
            <%= form_for @employee, html: { multipart: true } do |f| %>
                <%= render "shared/errors", object: @employee %>
                <div class="form-group">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name, :autofocus => true, :class => "form-control", 'aria-describedby' => "first_nameHelp", :placeholder => "Enter First Name" %>
                    <small id="first_nameHelp" class="form-text text-muted">Required field</small>
                </div>
                <div class="form-group">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name, :autofocus => true, :class => "form-control", 'aria-describedby' => "last_nameHelp", :placeholder => "Enter Last Name" %>
                    <small id="last_nameHelp" class="form-text text-muted">Required field</small>
                </div>
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, :class => "form-control", :placeholder => "Email" %>
                </div>
                <div class="form-group">
                    <%= f.label :phone %>
                    <%= f.text_field :phone, :class => "form-control", :placeholder => "Phone" %>
                </div>
                <%= f.label :company_id %>
                <select class="form-control" name="employee[company_id]">
                    <% @companies.each do |company| %> 
                        <option value="<%= company.id %>"><%=  company.name %></option>
                    <% end %>
                </select>
                <hr>
                <%= f.submit "Save", class: "btn btn-primary" %>
                <%= link_to "Back To Employees", employees_path, class: 'btn btn-secondary' %>
            <% end %>    
        </div>        
    </div>
</div>

app/views/employees/show.html.erb
<div class="container mt-4">
    
    <div class="row">
        <div class="col-offset-md-2 col-md-5">
        <% if flash[:notice] %>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong><%= flash[:notice] %></strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <% end %>
        <form id="add_employee_form">
            <%= render "shared/errors", object: @employee %>
            <div class="form-group">
                <label for="input_first_name">Firt Name</label>
                <input readonly type="text" class="form-control" id="input_first_name" value="<%= @employee.first_name %>">
            </div>
            <div class="form-group">
                <label for="input_last_name">Last Name</label>
                <input readonly type="text" class="form-control" id="input_last_name" value="<%= @employee.last_name %>">
            </div>
            <div class="form-group">
                <label for="input_email">Email</label>
                <input readonly type="text" class="form-control" id="input_email" value="<%=@employee.email%>">
            </div>
            <div class="form-group">
                <label for="input_phone">Phone</label>
                <input readonly type="text" class="form-control" id="input_phone" value="<%=@employee.phone%>">
            </div>
            <hr>
            <div class="form-group">
                <label for="input_company">Company</label>
                <input readonly type="text" class="form-control" id="input_company" value="<%= @employee.company.name %>">
            </div>
            <%= link_to "Back To Employees", employees_path, class: 'btn btn-secondary' %>
        </form>
        </div>    
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script> 
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
      <div class="container">
          <%= link_to "Companies&Employees", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <!-- Left Side Of Navbar -->
              <ul class="navbar-nav mr-auto">

              </ul>

              <!-- Right Side Of Navbar -->
              <ul class="navbar-nav ml-auto">
                  <!-- Authentication Links -->
                  <% if is_authenticated? %>
                    <li class="nav-item">
                      <%= link_to "Companies", companies_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Employees", employees_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        <%= current_user.email %><span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </li>
                  <% else %>
                    <li class="nav-item">
                        <%= link_to "Login", login_path, class: "nav-link" %>
                    <li class="nav-item">
                  <% end %>
              </ul>
          </div>
      </div>
  </nav>

  <%= yield %>

  </body>
</html>